options:
  permission: modemode.*
  prefix: &2&lMODMODE &7>>&r



command /modmode <text>:
  permission: {@permission}
  trigger:
    if arg-1 is "on":
      set {modmode.%player%} to "on"
      send "{@prefix} &2&lON"
    else:
      set {modmode.%player%} to "off"
      send "{@prefix} &c&lOFF"
      make console execute command "clear %player%"




command /modtools:
  permission: {@permission}
  trigger:
    give player lime dye named "&a&lVanish &e[RIGHT CLICK]"in slot 8
    epic
